### ISSUE TITLE
html5.ohtsu.org/ask_practice にアクセス時、エラーが表示される

### ISSUE THREAD

**Issue by narui1125** [shigeki/ask_practice#10]
## 概要
https://html5.ohtsu.org/ask_practice?name=foo にアクセスした際に、以下のエラーが表示されます。
```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

## 環境
- macOS 11.2.1 Safari 14.0.3

## 状況
- https://github.com/shigeki/ask_practice/tree/WIP/manual の ReadMe 内リンクよりアクセス

## 考えられる原因
必ずこの結果を返しているように思われます。

https://github.com/shigeki/ask_practice/blob/dfbc7912ad40eeed0d5cd0826b02e0e03525f32e/server/lib/router.js#L7-L9

**Comment by shigeki** [comment]
考えられる原因まで調査していただきありがとうございます。
はい、意図した挙動です。

課題が終わったのでクローズさせていただきます。
