### ISSUE TITLE
クエリパラメータを付与してもエラーが発生する

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [shigeki/ask_practice#11]
## エラー概要
[利用方法](https://github.com/shigeki/ask_practice/tree/WIP/manual) に従いクエリパラメータを付与したリクエストを送信したが、「システムに問題が発生しました」と表示される。

## 実行手順
1. https://html5.ohtsu.org/ask_practice に name=yukihoというクエリパラメータを付与して送信。実際のURL：https://html5.ohtsu.org/ask_practice?name=yukiho

## 予想する結果
「システムに問題が発生しました」と表示されないページに遷移する

## 実際の結果
以下のようなページが表示される
![image](https://user-images.githubusercontent.com/38527548/109778123-cbe16280-7c47-11eb-87f6-0c0615b81c57.png)

メッセージ本文
```
yukiho様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

## 実行環境
* windows 10
* Chrome 最新版

**Comment by shigeki** [comment]
スクリーンショットを貼ることは、客観的な証拠になるのでGoodポイントです。
課題が終わったのでクローズさせていただきます。
