### ISSUE TITLE
「システムに問題が発生」との文言が出る

### ISSUE THREAD

**Issue by ksk02** [shigeki/ask_practice#12]
**概要**
クエリパラメータに "?name=yahoo"をつけてアクセスしたところ、以下のエラー内容の文言が表示されます。
どのような対処をすればよろしいでしょうか？

**エラー内容**
「yahoo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください」

**手順**
GoogleChromeを用いて、以下のURLにアクセス。
[https://html5.ohtsu.org/ask_practice?name=yahoo](url)
概要で述べた文言が表示される。

**質問**
何かしらのホームページが表示されると思っていたのですが、実際にはエラー内容に書いた文言が表示されてしまいます。
ただ、issueの書き方の練習ということなので正しい表示ないかと考えていますが、間違い無いでしょうか？

**環境**
PC:macbook pro
OS: Catalina
ブラウザ:GoogleChrome

**Comment by shigeki** [comment]
各項目のリストベースで issue 出しているのはGoodポイントです。
環境についてはもう少し細かい情報（バージョン）など書いていただけると良かったかと。
課題が終わったのでクローズさせていただきます。
