### ISSUE TITLE
課題のurl先のシステムにおいて，「システムに問題が発生しました」と表示されました．

### ISSUE THREAD

**Issue by 0sa0sa** [shigeki/ask_practice#13]
・課題を解こうとhttps://github.com/shigeki/ask_practice にアクセスしたところ，「システムに問題が発生しました」と表示されました．

・実行手順
　・https://github.com/shigeki/ask_practice のurlにアクセス
　・操作に従い，https://github.com/shigeki/ask_practice?name=osa としてアクセス
　・エラー発生

・以下エラー内容
　・ osa様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
　
・環境
　・macOS Mojave version 10.14.6
　・safari 14.0.3

ご確認よろしくお願いします．

**Comment by shigeki** [comment]
実行手順をステップ化、エラー内容をちゃんとそのまま書いているのがGoodポイントです。
追加で期待する動作に関する記述があればよかったかと思います。

課題が終わったのでクローズさせていただきます。
