### ISSUE TITLE
「システムに問題が発生した」と表示される。

### ISSUE THREAD

**Issue by k1kk1** [shigeki/ask_practice#14]
「システムに問題が発生した」と表示される。

https://html5.ohtsu.org/ask_practice?name=kikki にアクセスしたところ、以下の文章が表示される。
>kikki様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

クエリパラメータを変更して実行しても同様のエラーメッセージが表示される。
- https://html5.ohtsu.org/ask_practice?name=kikki
- https://html5.ohtsu.org/ask_practice?name=こんにちは

実行環境：Google Chrome バージョン: 88.0.4324.190（Official Build） （64 ビット）

**Comment by shigeki** [comment]
時間が少なかったからでしょうが、もう少し説明(期待する動作等)が書いてあればよかったかなと思います。
課題が終わったのでクローズさせていただきます。
