### ISSUE TITLE
指定されたサーバにアクセスできない

### ISSUE THREAD

**Issue by nhiroyasu** [shigeki/ask_practice#15]
READMEで指示された通り、Ask Practice Serverにアクセスしてみたのですが、「システムに問題が発生しました」と表示されてしまいます。
アクセス時のURLは https://html5.ohtsu.org/ask_practice?name=hiro です。
サーバのホームページが表示されると思ったのですが、以下のような文面が表示されます。
**hiro様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください**
おそらく、サーバが正常に稼働していないと考えられます。

動作環境は
OS：macOS Big Sur
ブラウザ：Firefox version86.0
です。

よろしくお願いします。

**Comment by shigeki** [comment]
もう少し項目別に記述がまとめられていればわかりやすいかなと思います。

課題が終わったのでクローズさせていただきます。
