### ISSUE TITLE
ask_practiceにアクセスすると「システムに問題が発生しました」と表示される

### ISSUE THREAD

**Issue by hrntknr** [shigeki/ask_practice#16]
### 実行手順
1. https://github.com/shigeki/ask_practice/tree/WIP/manualを参照し、URLを作成
  作成したURL: https://html5.ohtsu.org/ask_practice?name=hrntknr
2. webブラウザから上記で作成したURLにアクセス

### 結果の予想
何かしらの正常なコンテンツが表示される

### 実際の結果
エラー画面が表示される

### ステップ明記
2.のURLにアクセスする手順のところでエラーが発生した。

### エラーメッセージ
```
hrntknr様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

### 環境
OS: ubuntu 21.04
Browser: google chrome Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by hrntknr** [comment]
サーバーのソースコードを確認したところ、以下の部分により必ずエラーメッセージが表示されるようになっていると考えられます。こちらは想定される挙動ということで正しいでしょうか？
https://github.com/shigeki/ask_practice/blob/742088d63e9b7953a255bfe63bf70903b05ae81c/server/lib/router.js#L7-L9

**Comment by shigeki** [comment]
リスト毎にわかりやすくまとめられているのがGoodです。
コードまで調べていただきまして、はい、想定している挙動です。
課題が終わりましたのでクローズさせていただきます。
