### ISSUE TITLE
Ask Practice Serverへのアクセスで「システムに問題が発生」と表示される

### ISSUE THREAD

**Issue by ymmtr6** [shigeki/ask_practice#17]
「素晴らしいページ」を表示するために，Ask Practice Server利用方法を参考にしてアクセスすると，システムに問題が発生しましたというメッセージが表示されました．
* 実行内容
https://html5.ohtsu.org/ask_practice?name=yamamoto
というリンクでアクセスすると，
```
yamamoto様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```
と表示されます．

* 期待する結果
「素晴らしいページ」が表示される．

実行環境: Chrome 88.0.4

**Comment by shigeki** [comment]
期待する結果が明確に書いてあるのがGoodポイントです。
環境に OS などがあるとなお良かったかも。
課題が終わりましたのでクローズさせていただきます。
