### ISSUE TITLE
Ask Practice Server 利用時にシステムの問題が発生

### ISSUE THREAD

**Issue by TakahiroSono** [shigeki/ask_practice#18]
表題 ―― あいさつではなく用件を書きましょう
システムの確認

書き出し ―― 最初に問題の要旨を書きましょう
Ask Practice Server利用時にシステムの問題が発生

実行手順 ―― 手順は箇条書きで書きましょう

- 利用例のURLでアクセス
- システムの問題が発生

結果の予想 ―― 期待した結果を書きましょう
実際の結果 ―― 実際に起きたことを書きましょう
システムの問題が発生

ステップ明記 ―― どこからうまく行かなくなったかを書きましょう
実際の値 ―― 条件を具体的に書きましょう

エラーメッセージ ―― 必ずコピー＆ペーストしましょう
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。

判断理由 ―― そのように考えた理由を書きましょう

環境 ―― 自分の環境をはっきり書きましょう
OS：mac OS Big Sur
ブラウザ：google chrome

**Comment by shigeki** [comment]
issue として書いてない余分な項目が書いてあるので少し読みにくいですね。
課題が終わりましたのでクローズさせていただきます。
