### ISSUE TITLE
https://html5.ohtsu.org/ask_practice?name=foo にアクセスできない

### ISSUE THREAD

**Issue by Msksgm** [shigeki/ask_practice#19]
https://html5.ohtsu.org/ask_practiceにニックネームfooでアクセスできない．

実行手順
- https://github.com/shigeki/ask_practice/tree/WIP/manualの手順に従った
- ニックネームをfooとした
- https://html5.ohtsu.org/ask_practice?name=foo にアクセス

実行結果
- サーバーにアクセスできるはずだったが，以下のようなエラーが表示された．
> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

実行環境
- OS: MacOS
- ブラウザ: Chrome

**Comment by shigeki** [comment]
アクセスという言葉での issue だと少し曖昧に思えます。
「素晴らしいページの表示」という方が今回の課題にあっているでしょう。
課題が終わりましたのでクローズさせていただきます。
