### ISSUE TITLE
Ask Practice Serverアクセス時，「システムに問題が発生した」と表示される

### ISSUE THREAD

**Issue by mkuroha** [shigeki/ask_practice#20]
【概要】
https://html5.ohtsu.org/ask_practice/?name=foo
にアクセスしましたが，「システムに問題が発生しました」と表示され，ページが正しく表示されませんでした．

【実行時の状況】
・https://html5.ohtsu.org/ask_practice 
　にアクセス
　↓
・「利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。」と表示され，指定URLにアクセス
　↓
・Ask Practice Server 利用方法通り，https://html5.ohtsu.org/ask_practice?name=foo にアクセス
　↓
・
> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。

と表示されました．

【実行環境】
・Windows10
・Chrome 88.0.4324.190

**Comment by shigeki** [comment]
「ページが正しく表示」という表現だとちょっと主観的な表現な感じがします。
「READMEに記載されている素晴らしいページが表示されない」といった方がはっきりしますね。
課題が終わりましたのでクローズさせていただきます。
