### ISSUE TITLE
サーバにアクセスする時にエラーメッセージが表示されます

### ISSUE THREAD

**Issue by Lunarslex** [shigeki/ask_practice#21]
大津様

Yushin Leeと申します。

https://github.com/shigeki/ask_practice/tree/WIP/manualに書いてある説明を参考に
https://html5.ohtsu.org/ask_practice?にアクセスしたところ、以下のエラーメッセージが表示されたので連絡いたしました。

Yushin様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。

アクセス時のシステム環境は以下の通りです。
OS: Windows 10 19042.804 (x86_64)
Browser: Chrome 89.0.4389.72

なお、ブラウザーの検証ツールにエラーは出ていません。

ご確認のほどよろしくお願いいたします。

Yushin Lee

**Comment by shigeki** [comment]
問題が再現できるよう、どのような引数でのアクセスをしたのか記述があればなお良いと思います。
課題が終わりましたのでクローズさせていただきます。
