### ISSUE TITLE
Ask practiceにアクセスした時に、エラーが提示されました

### ISSUE THREAD

**Issue by xuhaoddd** [shigeki/ask_practice#22]
ask practiceにアクセスした時に、エラーが発生しました

アクセスしたウェブサイトは：
`https://html5.ohtsu.org/ask_practice?name=Xu`　です

素晴らしいものがあるはずですが、実際にエラーが発生しました

エラーメッセージ は
`Xu様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください`　です

よろしくお願いします

**Comment by shigeki** [comment]
環境などの情報があればよかったかなと思いました。
課題が終わりましたのでクローズさせていただきます。
