### ISSUE TITLE
https://html5.ohtsu.org/ask_practice?name=fujita にアクセスしたところ、システムに問題が発生したとのメッセージが表示された

### ISSUE THREAD

**Issue by tomoyaf** [shigeki/ask_practice#23]
https://html5.ohtsu.org/ask_practice?name=fujita にアクセスし、なにか「素晴らしいページ」が表示されるとのことだったが、システムに問題が発生したとメッセージが表示されるばかりだった。

**実行結果**
`fujita様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください`

**素晴らしいページが表示されると考えた根拠**
https://github.com/shigeki/ask_practice/blob/WIP/README.md

**環境**
ブラウザ：Google Chrome 88.0.4324.192（Official Build） （x86_64）
OS：macOS Catalina 10.15.7

**Comment by shigeki** [comment]
完結で十分な表現だと思います。
課題が終わりましたのでクローズさせていただきます。
