### ISSUE TITLE
Ask Practice Serverにおけるシステム問題発生の問合せ

### ISSUE THREAD

**Issue by r-yanyo** [shigeki/ask_practice#24]
## 要件

https://html5.ohtsu.org/ask_practice?name=yanyo

上記のURLにアクセスしたところ、以下のエラーメッセージが表示されました。

> yanyo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

## 再現手順

1. はじめに、https://html5.ohtsu.org/ask_practice にアクセス
2. すると、以下のメッセージが表示されました。
> 利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。
3. manualを参照し、クエリパラメータに名前をつけて以下のようにアクセスしました。
> https://html5.ohtsu.org/ask_practice?name=yanyo
4. すると以下のようなエラーメッセージが表示されました。そのため、本issueにてお問い合わせをしております。
> yanyo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

## 環境
macOS
Chrome バージョン: 88.0.4324.192（Official Build） （x86_64）

試しに以下のブラウザで https://html5.ohtsu.org/ask_practice?name=yanyo にアクセスしたところ、同様の結果でした。
Firefox 85.0.2 
Safari バージョン14.0.3 (15610.4.3.1.6, 15610)

## コメント
Developer Toolでネットワークリクエストを見たところ、そこでは特にエラーは発生していません。

**Comment by shigeki** [comment]
ステップでの再現手順はGoodポイントです。マルチ環境での確認も素晴らしい。
課題が終わったのでクローズさせていただきます。
