### ISSUE TITLE
Ask Practice Server のアクセス時に「システムに問題が発生しました」となる

### ISSUE THREAD

**Issue by nicked4** [shigeki/ask_practice#25]
Ask Practice Server 利用方法（https://github.com/shigeki/ask_practice/tree/WIP/manual ）に従って https://html5.ohtsu.org/ask_practice?name=foo にアクセスしましたが、下記のメッセージとともに失敗します。

> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

OSはwindows10、ブラウザはgoogle chromeで実行しています。

**Comment by shigeki** [comment]
> 下記のメッセージとともに失敗します。

失敗をもう少し客観的にわかってもらうために、期待する結果が書いてあればよかったかなと思います。
課題が終わったのでクローズさせていただきます。
