### ISSUE TITLE
ページのアクセスエラーの問題

### ISSUE THREAD

**Issue by gidoichi** [shigeki/ask_practice#26]
Ask Practice Serverアクセス時に「システムに問題が発生しました」というエラーが出ました

[利用方法](https://github.com/shigeki/ask_practice/tree/WIP/manual) を見て下記の手順で試しました。
1. ブラウザで https://html5.ohtsu.org/ask_practice?name=foo にアクセス

上記実行結果としてニックネーム「foo」で「素晴らしいページ」にアクセスできることが予想されますが，下記のエラーメッセージが出てしまいます。

> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

「システムに問題が」と言っていることころから、サーバ内部になんらかの問題が発生しているものと考えられます。

環境は下記の通りです。「素晴らしいページ」へのアクセス方法を教えていただければ幸いです。

**環境**
OS：Windows 10 Home
ブラウザ：Google Chrome バージョン: 89.0.4389.72（Official Build）（64ビット）

**Comment by shigeki** [comment]
簡潔にまとめられていると思います。
課題が終わったのでクローズさせていただきます。
