### ISSUE TITLE
Ask Practice Serverのエラー発生について

### ISSUE THREAD

**Issue by nkchan** [shigeki/ask_practice#27]
https://html5.ohtsu.org/ask_practice へのアクセスを行いましたがエラーでページを参照することができませんでした．
今回はsafari 14.0.3で確認をしております．

手順1: https://html5.ohtsu.org/ask_practice ヘアクセス

表示されたエラー
```
利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。
```

手順2: 上記マニュアルにアクセス後，参考例として挙げられている `https://html5.ohtsu.org/ask_practice?name=foo` にアクセスする

表示されたエラー
```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

というメッセージが出ています．マニュアル通りにアクセスすることでアクセスを行うことが可能であると考えていましたが，上記のようなエラーが帰ってきました．

そのため，サーバ側のエラーでは無いかと考えております．サーバが正常に動作しているかを確認してもらえると幸いです．

**Comment by shigeki** [comment]
手順がステップ化されているのはGoodポイントです。
OSとバージョンなどの環境があれば良いかなと思いました。
課題が終わったのでクローズさせていただきます。
