### ISSUE TITLE
素晴らしいページにてnameクエリを指定してアクセスした際にシステムエラーの文言が表示される

### ISSUE THREAD

**Issue by maitaken** [shigeki/ask_practice#28]
# 要旨
素晴らしいページ(`https://html5.ohtsu.org/ask_practice`)にアクセスしましたところ、システムに問題が発生したとの文言が表示された

# 条件
以下の手順・条件でアクセスを行いました。
1.マニュアル(`https://github.com/shigeki/ask_practice/tree/WIP/manual`)に記載されているアクセス例をコピー
2.ブラウザのURL欄に貼り付けて検索
3. 下記画像にありますシステムエラーの文言が表示

ここで使用したnameのquery parameterにはマニュアルにありました例(name=foo)を使用しております。

# エラー
上記の3の手順の後に以下の画面が表示されております。
<img width="1137" alt="スクリーンショット 2021-03-03 17 39 51" src="https://user-images.githubusercontent.com/32431220/109777824-786f1480-7c47-11eb-9d0d-0028b3ca8ff9.png">

# 環境
OS : MacOS Catalina
ブラウザ : Google Chrom  (88.0.4324.192)

**Comment by shigeki** [comment]
スクリーンショットは客観的なデータなのでこれの付加はGoodポイントです。
課題が終わったのでクローズさせていただきます。
