### ISSUE TITLE
正規の手順に従っても素晴らしいページが表示されない．

### ISSUE THREAD

**Issue by ttak0422** [shigeki/ask_practice#29]
## 実行手順

READMEの指示に従い`https://html5.ohtsu.org/ask_practice `をブラウザに入力すると，マニュアルを参照するように指示される．

マニュアルに従い`https://html5.ohtsu.org/ask_practice?name=foo`と入力するも依然として問題が生じる．

![image](https://user-images.githubusercontent.com/15827817/109778402-1e228380-7c48-11eb-817e-bc1b6f0a71f6.png)

## 期待した結果

素晴らしいページが表示される．

## 環境

Chrome 88.0.4324.192（Official Build） （x86_64）

**Comment by shigeki** [comment]
スクリーンショットは客観的なデータなのでGoodポイントです。
環境に関してはOS＋バージョンなどもあればなお良かったかなと思います。
課題が終わったのでクローズさせていただきます。
