### ISSUE TITLE
意図した動作をしていると思いました

### ISSUE THREAD

**Issue by 2754github** [shigeki/ask_practice#30]
`ask_practice/server/lib/router.js` を見る限り意図した動作をしていると思いました。
こういうことでしょうか？

```
const getHandler = (req, res) => {
  if (!req.query.name) {
    res.send(`利用方法が違うようです。<a href="https://github.com/shigeki/ask_practice/tree/WIP/manual">https://github.com/shigeki/ask_practice/tree/WIP/manual</a> を参照の上、再度アクセスしてください。`);
    return;
  }
  const name = req.query.name;
  res.header('Content-Type', 'text/html;charset=utf-8');
- res.send(`${name}様: 申し訳ございません。システムに問題が発生しましたので <a href="https://github.com/shigeki/ask_practice/issues">https://github.com/shigeki/ask_practice/issues</a> までお問い合わせください。github使いたくない、もしくはアカウントのない方は <a href="https://html5.ohtsu.org/question.html">https://html5.ohtsu.org/question.html</a> までお問い合わせください`);
+ res.send("素晴らしいページ");
};

...
```

**Comment by 2754github** [comment]
題意が汲み取れてませんでした 😰（バグがあるのかと思って探してしまいました）

余談ですが、自分はいつも以下のテンプレートを使ったり、使ってもらったりしています。

---

# 質問表テンプレート

# 現在の状況（やりたいこと&出ているエラー等）

現在、ログイン機能を実装しているのですが`AbstractController::DoubleRenderError`というエラーが出ます 😭

# どのように実装したか&その結果

### 関連があると思う使用技術

- `使用言語`: Ruby
- `フレームワーク`: Ruby on Rails
- `ライブラリ`: devise

### 関連があると思うソースコード

> ここに、 GitHub 上のファイルへのリンクを貼る（リポジトリやコミットの単位でも良い 👌）

### 結果

> ここに、Web ブラウザ、VSCode、ターミナル等に表示されたエラー画面のキャプチャへの Gyazo リンクを貼る

# 調べた内容&そこから立てた仮説

上記のエラーを解決するために、以下のキーワードで検索しました。

- AbstractController::DoubleRenderError
- DoubleRenderError devise
- ...

調べた結果、原因は以下ではないかと考えています 🤔

> ここに、あなたの仮説を書いてみる（間違っていても良い 👌）

# 仮説を元に行った検証&その結果

検索で出てきた情報のうち、

- https://qiita.com/katsuyuki/items/abf6b8d1cd43915e5586
- ...

を参考にして、当該箇所に`and return`を追加してみましたが、解決には至らず、以下の結果となりました。

> ここに、Web ブラウザ、VSCode、ターミナル等に表示されたエラー画面のキャプチャへの Gyazo リンクを貼る

**Comment by shigeki** [comment]
サーバのコードは意図した動作ですが、課題自体は以下の通りの記述にしています。

```
課題
https://html5.ohtsu.org/ask_practice にアクセスすると、なにか「素晴らしいページ」が表示されるはずです。

「素晴らしいページ」が表示されない場合は、画面の指示に従ってください。
```

課題をベースに issue を出していただくのが意図でしたが、題意を読み取っていただけなかったのは残念でした。
課題が終わったのでクローズさせていただきます。
