### ISSUE TITLE
Ask Practice Serverにアクセスすると”システムに問題が発生しました”と表示されます．

### ISSUE THREAD

**Issue by naoki-nk** [shigeki/ask_practice#31]
name の query parameterとして"foo"とすると，以下のエラーが表示さえます．
---
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。
---
実行環境は，macOS で，Safari versionは14.0.1です．
よろしくお願いします．

**Comment by shigeki** [comment]
もう少し詳しくステップなど書いてあれば良いかなと思いました。
課題が終わりましたのでクローズさせていただきます。
