### ISSUE TITLE
Ask Practice Server　システムに問題が発生と表示される

### ISSUE THREAD

**Issue by marblet** [shigeki/ask_practice#32]
### 状況
[Ask Practice Server利用方法](https://github.com/shigeki/ask_practice/tree/WIP/manual)を参照し、https://html5.ohtsu.org/ask_practice?name=foo にアクセスしたところ、以下のメッセージが表示されました。
```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```
nameパラメータに"hoge"や"aaaa"などを入力しても同様のエラーメッセージが表示されました。

「素晴らしいページ」が表示されると期待していたのですが、なにか設定等間違っているのでしょうか。

### 環境
- Windows 10
- Google Chrome バージョン: 88.0.4324.190（Official Build） （64 ビット）

**Comment by shigeki** [comment]
簡潔な issue で十分な情報を含んでいると思います。
課題が終わりましたのでクローズさせていただきます。
