### ISSUE TITLE
Ask Practice Serverへのアクセス時に「システムに問題が発生しました」と表示される

### ISSUE THREAD

**Issue by felix925** [shigeki/ask_practice#34]
### 起こった問題
`https://html5.ohtsu.org/ask_practice?name=anyone`
へのアクセス時に
`anyone様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください`
と言うページが表示されます。
### 使用環境
使用環境は、Google Chromeでバージョンは88.0.4324.192です。

### エラーに至った手順
https://github.com/shigeki/ask_practice/tree/WIP/manual を参照した上で、https://html5.ohtsu.org/ask_practice?name=anyoneのようにアクセスを行いました。

### 期待される結果
素晴らしいページが表示されることが期待されますが、実際はシステムに問題が発生した旨のページが表示され、素晴らしいページは表示されませんでした。

### 現時点で考えられる事象
nameのパラメータを渡すことは、エラーページにanyone様と表示されていることや、クエリを変更してもエラーページの文章の名前部分に反映されているためそこで問題は起こっていないと考えられます。

**Comment by shigeki** [comment]
主観的に書かれている「考えられる事象」など別に記載されているのが良いポイントだと思います。
課題が終わりましたのでクローズさせていただきます。
