### ISSUE TITLE
ask practiceの指示に従っても「素晴らしいページ」にアクセスできない

### ISSUE THREAD

**Issue by k22o** [shigeki/ask_practice#35]
https://html5.ohtsu.org/ask_practice にアクセスできませんでした．

以下のような手順で解決を試みましたが，正規のページにアクセスできませんでした．
- https://github.com/shigeki/ask_practice/tree/WIP/manualの指示を参照
- `name=foo` として https://html5.ohtsu.org/ask_practice?name=foo にアクセス
- 同様にシステムに障害が発生

```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

実行環境：
OS: Windows 10
ブラウザ: Chrome 88.0.4324.190

**Comment by shigeki** [comment]
「アクセスできない」という表現が具体的に何を期待しているのか記述されていればより良いと思います。
課題が終わりましたのでクローズさせていただきます。
