### ISSUE TITLE
nameパラメーターを付与時にエラー画面が表示される

### ISSUE THREAD

**Issue by ksprout** [shigeki/ask_practice#36]
`Ask Practice Server` にアクセスしたところ、エラー画面が表示されます。

- URL：https://html5.ohtsu.org/ask_practice?name=tanigawa
- Chromeのアドレスバーに直接入力してアクセスした

利用方法を参照すると、要件としてname の query parameter が必要と記載されていますが、
エラーが発生してしまいます。

エラーメッセージ：
```
tanigawa様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

nameパラメーターの文字数制限やプログラムで正しく受け取れていないことなどが必要だと考えられます。

---
実行環境：Windows 10 、Chrome 88

**Comment by shigeki** [comment]
> Chromeのアドレスバーに直接入力してアクセスした

入力方法までちゃんと書かれていることはGoodポイントだと思います。
課題が終わりましたのでクローズさせていただきます。
