### ISSUE TITLE
システムに問題が発生

### ISSUE THREAD

**Issue by rainbartown** [shigeki/ask_practice#37]
# 発生した問題
https://github.com/shigeki/ask_practice/tree/WIP/manual の `README.md` に従って https://html5.ohtsu.org/ask_practice?name=rainbartown にアクセスすると，
  > 利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。

と表示される．

# 環境
- MacOS Big Sur 11.2.1
- GoogleChrome 88.0.4324.192（Official Build） （x86_64）

**Comment by shigeki** [comment]
非常に簡潔ですが期待する結果などがあるとよかったかなと思います。
課題が終わりましたのでクローズさせていただきます。
