### ISSUE TITLE
Ask Practice Serverにアクセス時にシステムに問題が発生したと表示されます

### ISSUE THREAD

**Issue by Hironori8** [shigeki/ask_practice#38]
Ask Practice Serverにアクセス時にシステムに問題が発生したと表示されます

実行手順 

1. https://html5.ohtsu.org/ask_practiceにアクセス

2. https://github.com/shigeki/ask_practice/tree/WIP/manualにアクセス

3. https://html5.ohtsu.org/ask_practice?name=fooでアクセスしたところシステムに問題が発生したと表示

結果の予想 

https://html5.ohtsu.org/ask_practice?name=fooでAsk Practice Server 利用ができると予想していました。

実際の結果 

システムに問題が発生したと表示されます。

ステップ明記 

https://html5.ohtsu.org/ask_practice?name=fooのnameパラメータの受け渡しでうまくかなかったと考えています。

エラーメッセージ 

foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

環境 

Google Chromeバージョン: 88.0.4324.192

**Comment by shigeki** [comment]
手順がステップ化されて記載されているのはとても良いと思います。

> Ask Practice Server 利用ができると予想していました。

何をもって「利用できる」と表現されているのかちょっと曖昧なので、もう少し具体的な期待する結果が書いてあると良いと思います。

課題が終わりましたのでクローズさせていただきます。
