### ISSUE TITLE
ask_practice ページでエラーが発生する

### ISSUE THREAD

**Issue by koba1t** [shigeki/ask_practice#39]
ask_practice のページにアクセスした際に、システムに問題が発生したというエラーが表示され、正しくページが表示されない。

# 手順
- `https://html5.ohtsu.org/ask_practice` にアクセスした所、利用方法の[案内](https://github.com/shigeki/ask_practice/tree/WIP/manual) が表示された。
- 上記の案内に従い、ニックネームを指定してアクセスを試みた。
- 自分のニックネームをパラメータに付けてアクセスした所、`システムに問題が発生した` というエラーが表示された。

# 実際にアクセスしたページ
```
https://html5.ohtsu.org/ask_practice?name=kob
```

# エラーメッセージ
```
kob様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

# 検証?
curlを使用しpostメソッドで送った所、おそらく正しいと思われる返答が返された?
```
curl "https://html5.ohtsu.org/ask_practice?name=kob" -d "hoge"
問い合わせありがとうございました。%  
```

# 環境
```
browser: Firefox 85.0
OS: Archlinux
```

**Comment by shigeki** [comment]
手順を箇条書きをしているのがGoodポイントだと思います。
検証については 課題がGETによるURLのアクセスであり、POST データの処理は問い合わせフォームの返答ページの一部が出ているだけです。
課題が終わりましたのでクローズさせていただきます。
