### ISSUE TITLE
Ask Practice Serverへのアクセス時に「システムに問題が発生しました」と表示されます

### ISSUE THREAD

**Issue by jre233kei** [shigeki/ask_practice#4]
大津様

はじめまして、Ask Practiceに参加しているものです。

以下のURLにアクセスしたところ、下記のようなメッセージが発生しました。
`https://html5.ohtsu.org/ask_practice?name=kotaf`

```kotaf様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください```

検証ツール上には特にエラーがありません。

使用してる環境は以下の通りです。
OS          : MacOS10.13
ブラウザ: Google Chrome 88.0.4324.192

ご確認のほどよろしくお願いいたします。

**Comment by shigeki** [comment]
問い合わせありがとうございます。
環境およびメッセージを明確に伝えていただいたのが良いと思います。
検証ツールでのエラーへの言及はなかなかプラスなポイントです。
課題が終わったので、クローズさせていただきます。
