### ISSUE TITLE
Ask Practice Serverにアクセスする時に，システムで問題が発生したと表示される

### ISSUE THREAD

**Issue by cis-yuta** [shigeki/ask_practice#40]
表題の通り，Ask Practice Serverにアクセスしたが，システムに問題が発生したと表示されました．

初めに，https://html5.ohtsu.org/ask_practiceにアクセスしたところ，https://github.com/shigeki/ask_practice/tree/WIP/manualを参照に再度アクセスするように表示されました．
そのため，https://github.com/shigeki/ask_practice/tree/WIP/manualに従い，https://html5.ohtsu.org/ask_practiceにname=fooとクエリを追加し，https://html5.ohtsu.org/ask_practice?name=fooとし，アクセスしたところ以下のメッセージが表示されました．

>foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

課題に書かれているように，「素晴らしいページ」にアクセスができると予想していたのですが，どこか間違えているでしょうか．

環境はWindows10，chromeを使用しています．

**Comment by shigeki** [comment]
表題をわかりやすく変えていることはGoodポイントです。
手順はできるだけ箇条書きにするともう少しわかりやすくなるかと思います。
課題が終わりましたのでクローズさせていただきます。
