### ISSUE TITLE
Ask Practice Serverアクセス時に「システムに問題が発生」と表示

### ISSUE THREAD

**Issue by Gosshi** [shigeki/ask_practice#41]
shigeki様

以下のURLにアクセスしたところ，システムに問題が発生したとエラーが表示され，素晴らしいページの表示ができませんでした．
https://html5.ohtsu.org/ask_practice?name=gota

エラー内容は以下の通りです．
`gota様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください`

README記載のURL(https://html5.ohtsu.org/ask_practice )から遷移し，遷移先
（https://github.com/shigeki/ask_practice/tree/WIP/manual） の指示に従って名前のパラメータを付与したのですが，なにか見落とし等ありましたら，ご教示いただけますと幸いです．

実行環境・アクセス日時は以下の通りです．
OS:Windows10
ブラウザ：Opera GX  LVL2 (core: 73.0.3856.400)
日時：2021年3月3日 17時50分(JST)

どうぞよろしくお願いいたします．

**Comment by shigeki** [comment]
アクセス日時を記載されているのは非常に評価高いです。
課題が終わりましたのでクローズさせていただきます。
