### ISSUE TITLE
素晴らしいページにアクセスできません

### ISSUE THREAD

**Issue by kanon22** [shigeki/ask_practice#42]
2021年3月3日17時35分ごろ，システムにアクセスしたところ，
問題が発生して「素晴らしいページ」が表示されませんでした．

https://html5.ohtsu.org/ask_practice?name=kanon22 で「素晴らしいページ」が表示されると予想しましたが，
システムに問題が発生した旨のエラーが表示されました．
「素晴らしいページ」にアクセスする方法を教えていただきたいです．

実行手順は以下のとおりです．
- https://html5.ohtsu.org/ask_practice にアクセス
- 「利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。」との表示にしたがって https://github.com/shigeki/ask_practice/tree/WIP/manual にアクセス
- 上のページの指示通り，nameのquery parameterをkanon22として， https://html5.ohtsu.org/ask_practice?name=kanon22 にアクセス
- 下記のエラーメッセージが表示される

https://html5.ohtsu.org/ask_practice?name=kanon22 にて表示されたエラーメッセージ
```kanon22様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください```

実行環境
Mac OS Catalina, Braveブラウザ

**Comment by shigeki** [comment]
アクセス時刻が書いてあるのは非常にポイント高いです。
せっかく環境が書いてあるならバージョンまで記載されているとなお良いと思います。
課題が終わりましたのでクローズさせていただきます。
