### ISSUE TITLE
ask_practiceで発生するシステムエラーについて

### ISSUE THREAD

**Issue by PajamaDrive** [shigeki/ask_practice#43]
nameを指定してアクセスしましたが，素晴らしいページが表示されません．

### 実行手順
1. https://html5.ohtsu.org/ask_practice にアクセス
2. 利用方法が違う旨が表示される
3. https://github.com/shigeki/ask_practice/tree/WIP/manual  の内容を参照し，name属性を指定してhttps://html5.ohtsu.org/ask_practiceにアクセス

### 実行結果
name属性を追加することで素晴らしいページが表示されるはずですが，システムの問題が発生したと表示されました．
name=foo，name=hogeで試しましたがどちらもアクセスできませんでした．

### name=fooの場合
> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
### name=hogeの場合
> hoge様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

### 実行環境
OS:Mac OS 11.2.1
ブラウザ:Google Chrome 88.0.4324.150

**Comment by shigeki** [comment]
項目をリスト化して記載されていることはGoodポイントです。
またパターンを分けて試験結果を書いているのもGoodです。
課題が終わりましたのでクローズさせていただきます。
