### ISSUE TITLE
Ask Practice Server アクセス時にエラーメッセージが表示されます

### ISSUE THREAD

**Issue by Axion243** [shigeki/ask_practice#44]
#### 概要

name の query parameter を temp として
https://html5.ohtsu.org/ask_practice?name=temp
にアクセスしたところ、

> temp様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

というエラーメッセージが表示されました。

#### 手順

1. https://github.com/shigeki/ask_practice へアクセス

2. 以下のメッセージが表示される

    >利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。

3. https://github.com/shigeki/ask_practice/tree/WIP/manual を参照し、"?name=temp" の query parameter を付与して再度アクセスすると上記のエラーメッセージが表示される

#### 環境
OS: Windows 10 Pro
Browser: Chrome 89.0.4389.72

**Comment by shigeki** [comment]
手順をステップ化して記述しているのはGoodポイントです。
タイトルを見直してより良く修正しているもの良い心がけだと思います。
課題が終わりましたのでクローズさせていただきます。
