### ISSUE TITLE
サーバーにアクセスできない

### ISSUE THREAD

**Issue by piraaa** [shigeki/ask_practice#45]
Ask Practice Serverにアクセスを試みましたが「システムに問題が発生しました」と表示されてしまいページが表示されません．

1. [README](https://github.com/shigeki/ask_practice/blob/WIP/manual/README.md) を参照してニックネームを"test"に設定
2. ブラウザから https://html5.ohtsu.org/ask_practice?name=test にアクセスしたところエラーメッセージが表示された

エラーメッセージ：
```
test様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

実行環境：
Windows10 バージョン1909
Google Chrome バージョン: 89.0.4389.72

**Comment by shigeki** [comment]
> ページが表示されません．

何のページの表示を期待しているのか書いてあると良いと思います。

課題が終わりましたのでクローズさせていただきます。
