### ISSUE TITLE
Ask Practice Serverにアクセスすると，「システムに問題が発生しました」と表示される．

### ISSUE THREAD

**Issue by yotaroy** [shigeki/ask_practice#46]
`https://github.com/shigeki/ask_practice/tree/WIP/manual`に従い，Ask Practice Serverにアクセスすると，「システムに問題が発生しました」と表示されます．

`https://html5.ohtsu.org/ask_practice?name=yotaroy`
にアクセスすると，
```
yotaroy様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```
と表示されます．

## 環境
chrome 88.0.4324.192（Official Build） （x86_64）
Mac

**Comment by shigeki** [comment]
何を期待していたことができないのか書いてあると良いと思います。

課題が終わりましたのでクローズさせていただきます。
