### ISSUE TITLE
システムに問題が発生しました

### ISSUE THREAD

**Issue by msmtt** [shigeki/ask_practice#47]
利用方法にしたがって素晴らしいページにアクセスしましたが、問題が発生しアクセスできませんでした。

# 実行手順
アクセス方法は以下の通りになります
```
https://html5.ohtsu.org/ask_practice?name=foo
```

リクエストにnameを設定しましたが、以下の結果が表示されました。

# 結果
```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

# 環境
macOS Big Sur 
version11.2.1

**Comment by shigeki** [comment]
「アクセスできない」という表現は少し曖昧なので明確に何を期待した結果にならないのか書いてあると良いかと思います。

課題が終わりましたのでクローズさせていただきます。
