### ISSUE TITLE
webサイトが正常に表示されない件について

### ISSUE THREAD

**Issue by hiyashinsudo** [shigeki/ask_practice#48]
[ここ](https://html5.ohtsu.org/ask_practice)にアクセスすると，「利用方法が違うようです。
https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。」と表示されます．

### 実行手順

1. GoogleChromeを使用．
2. "https://github.com/shigeki/ask_practice"の下部あるwebサイトにアクセス
3. https://html5.ohtsu.org/ask_practiceに移行
4. webサイトを表示

### 実行結果
「利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。」と表示されます．

### 期待される結果
「素晴らしいページ」が表示されるはずです．

### ステップ
おそらくステップ4で異常が発生したと思われます．

### 実行環境
OS：macOS Big Sur ver 11.2.2
Web Browser：Google Chrome バージョン: 88.0.4324.192（Official Build） （arm64）

**Comment by shigeki** [comment]
内容は項目別に完結に書いてあるのでGoodです。
ただタイトルの「正常に表示」に関しては何を正常とするのか曖昧な言葉になるのでもう少し明確なタイトルにすればよいかと思います。

課題が終わりましたのでクローズさせていただきます。
