### ISSUE TITLE
Ask Practice Server へのアクセス時にエラーメッセージが表示される

### ISSUE THREAD

**Issue by Hamchin** [shigeki/ask_practice#49]
Ask Practice Server にアクセスしたところ、「システムに問題が発生した」とのメッセージが表示され、想定していた「素晴らしいページ」にアクセスすることができませんでした。

## 実行手順

1. https://github.com/shigeki/ask_practice にアクセスする。

2. README.md 内の下記指示に従って https://html5.ohtsu.org/ask_practice にアクセスする。
> https://html5.ohtsu.org/ask_practice にアクセスすると、なにか「素晴らしいページ」が表示されるはずです。
> 「素晴らしいページ」が表示されない場合は、画面の指示に従ってください。

3. 下記メッセージが表示され、そちらに従って https://github.com/shigeki/ask_practice/tree/WIP/manual にアクセスする。
> 利用方法が違うようです。https://github.com/shigeki/ask_practice/tree/WIP/manual を参照の上、再度アクセスしてください。

4. README.md 内の下記指示に従って https://html5.ohtsu.org/ask_practice?name=foo にアクセスする。
> サーバにアクセスする場合には、name の query parameter が必要です。なにか好きなニックネームをnameに付けてアクセスしてください。

## 結果

上記実行手順に従ったところ、下記メッセージが表示される。

> foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

## 環境

- OS: macOS 11.2.2
- ブラウザ: Google Chrome 88.0.4324.192

**Comment by shigeki** [comment]
項目別にまとめられ、簡潔に十分記載されていると思います。
課題が終わりましたのでクローズさせていただきます。
