### ISSUE TITLE
Ask Practice Server にアクセスしたところシステムに問題が発生したとのメッセージが出た。

### ISSUE THREAD

**Issue by y-kisse** [shigeki/ask_practice#5]
表題の通りAsk Practice Server にアクセスしたところシステムに問題が発生したとのメッセージが出ました。

https://github.com/shigeki/ask_practice/tree/WIP/manual を参照し、https://html5.ohtsu.org/ask_practice?name=foo のようにクエリパラメータに name=foo を指定してアクセスをしたところ以下のメッセージが返ってきました。

```
foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

何かしら「素晴らしいメッセージ」が返ってくると期待していたのですが、何かURLクエリパラメータに設定すべき項目が間違ってますでしょうか。

環境は Windows10, Chrome です。

**Comment by shigeki** [comment]
問い合わせありがとうございます。

期待した動作を書いていただいたのはGoodポイントです。
環境では Chrome のバージョンを書いていただけるとなお良かったかと思います（バージョン依存の問題ではないとの確証があったならべですが）。

課題が終わりましたのでクローズさせていただきます。
