### ISSUE TITLE
ask_practiceへアクセスするとシステムに問題が発生する

### ISSUE THREAD

**Issue by kato-hiroto** [shigeki/ask_practice#6]
https://html5.ohtsu.org/ask_practice?name=foo にアクセスすると，システムに問題が発生したと表示されます．

実行手順
1. https://html5.ohtsu.org/ask_practice にアクセスする
2. 利用方法が違うと表示されるため，指示に従いマニュアルへアクセスする
3. name の query parameter を付加して再度アクセスする ( https://html5.ohtsu.org/ask_practice?name=foo へアクセス)
4. foo様: 申し訳ございません。… という画面が表示される

期待した結果
素晴らしいページの表示

エラーメッセージ 
`foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください`

環境 
Vivaldi | 3.5.2115.81 (Stable channel) (64-bit)

**Comment by shigeki** [comment]
項目毎のリストで記述されているのはGoodポイントだと思います。
環境の Vivaldi は珍しい。

課題が終わったのでクローズさせていただきます。
