### ISSUE TITLE
aks_practiceにアクセスしたが「素晴らしいページ」が表示されない

### ISSUE THREAD

**Issue by akimash** [shigeki/ask_practice#7]
https://html5.ohtsu.org/ask_practice?name=foo にアクセスしたのですが、本来表示されるであろう「素晴らしいページ」が表示されず、利用方法が違う旨が表示されます。

- 実行手順
  - https://github.com/shigeki/ask_practice/tree/WIP/manual を見て、fooというニックネームを使うため、https://html5.ohtsu.org/ask_practice?name=foo にアクセスしました。

- 実際の値
  > foo様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください

- 環境
  - OS Windows10 Home バージョン2004(OSビルド 19041.804)
  - ブラウザ Vivaldi

**Comment by shigeki** [comment]
タイトルをわかりやすく修正していることが素晴らしい。
一度出した issue もちゃんと見直す姿勢は大事です。
課題が終わったのでクローズします。
