### ISSUE TITLE
https://html5.ohtsu.org/ask_practice ページでの問題の問い合わせ

### ISSUE THREAD

**Issue by sh05** [shigeki/ask_practice#8]
https://html5.ohtsu.org/ask_practice?name=hello のURLで問題が発生したため問い合わせました。

1. google chrome のアドレスバーに https://html5.ohtsu.org/ask_practice?name=hello を打ち込みアクセスしました。

ページコンテンツの表示を期待したところ、
> hello様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください  
と表示されました。

私は https://github.com/shigeki/ask_practice/tree/WIP/manual を見て name の query parameter を`hello`としてアクセスしました。

環境は
- Mac OS Big Sur 11.2.2
- Google Chrome バージョン: 88.0.4324.192（Official Build） （x86_64）

よろしくお願いします

**Comment by shigeki** [comment]
期待した動作や結果・再現方法まで書かれているのはGoodポイントです。
タイトルをもう少しわかりやすくしないともしかしたら埋もれてしまう可能性があるかなと思いました。
課題が終わったのでクローズさせていただきます。
