### ISSUE TITLE
html5.ohtsu.org/ask_practice が表示されない

### ISSUE THREAD

**Issue by gihachi** [shigeki/ask_practice#9]
https://github.com/shigeki/ask_practice/tree/WIP/manual にて指定された方法で素晴らしいページを表示しようとしてのですが，うまく表示されませんでした．

## 実行した手順

1. query parameterにishidaを指定して https://html5.ohtsu.org/ask_practice にアクセス
    - url : https://html5.ohtsu.org/ask_practice?name=ishida

## 期待した結果

素晴らしいページが表示される

## 実際の結果

素晴らしいページが表示されずエラー画面が表示されました

### エラーメッセージ

```
ishida様: 申し訳ございません。システムに問題が発生しましたので https://github.com/shigeki/ask_practice/issues までお問い合わせください。github使いたくない、もしくはアカウントのない方は https://html5.ohtsu.org/question.html までお問い合わせください
```

## 環境

Google Chromeにてアクセスしました

**Comment by shigeki** [comment]
項目リストごとで記述しているのは Goodポイントです。
環境は OS, Chrome バージョン等を書いていただけるともっと良かった。
課題が終わったのでクローズさせていただきます。
